on:
  workflow_dispatch:

name: Benchmark

env:
  GOPRIVATE: "github.com/yousuf-git/dune-project"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.19'
        cache: true
    - uses: actions/checkout@v3
    - run: go test -bench .
